version: '3'
services:
  db:
    container_name: es_db
    image: mysql:8.0
    volumes:
      - ./sql/mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      DB_USER: "${DB_USER}"
      DB_PORT: "${DB_PORT:-3306}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
  app:
    container_name: es_backend
    build: 
      context: ./app
      dockerfile: Dockerfile
      args:
        DB_HOST: db
        DB_USER: "${DB_USER}"
        DB_PASSWORD: "${DB_PASSWORD}"
        DB_SCHEMA: "${DB_DATABASE}"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./app/${APP_NAME}:/src
    ports:
      - "${APP_PORT:-8000}:8000"